# Generated by Django 4.1.7 on 2023-04-07 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import main.utilities


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rubric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=225, unique=True, verbose_name="Name"
                    ),
                ),
                (
                    "order",
                    models.SmallIntegerField(
                        db_index=True, default=0, verbose_name="Order"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Question")),
                ("content", models.TextField(verbose_name="Answer")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Show?"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to=main.utilities.get_timestamp_path,
                        verbose_name="Image",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Published"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdditionalImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=main.utilities.get_timestamp_path,
                        verbose_name="Image",
                    ),
                ),
                (
                    "bb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.article",
                        verbose_name="The note",
                    ),
                ),
            ],
            options={
                "verbose_name": "Additional Image",
                "verbose_name_plural": "Additional Images",
            },
        ),
        migrations.CreateModel(
            name="SubRubric",
            fields=[],
            options={
                "verbose_name": "Sub_rubric",
                "verbose_name_plural": "Sub_rubrics",
                "ordering": (
                    "super_rubric__order",
                    "super_rubric__name",
                    "order",
                    "name",
                ),
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("main.rubric",),
            managers=[("object", django.db.models.manager.Manager()),],
        ),
        migrations.CreateModel(
            name="SuperRubric",
            fields=[],
            options={
                "verbose_name": "Sub_rubric",
                "verbose_name_plural": "Sub_rubrics",
                "ordering": ("order", "name"),
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("main.rubric",),
            managers=[("object", django.db.models.manager.Manager()),],
        ),
        migrations.AddField(
            model_name="rubric",
            name="super_rubric",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.superrubric",
                verbose_name="Super_rubric",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="rubric",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="main.subrubric",
                verbose_name="Rubric",
            ),
        ),
    ]
